package corpse;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.util.regex.Matcher;

import file.FileUtils;

public final class Depends
{
   private static File outFile;

   private Depends() { }
   
   private static void processDir (final PrintWriter out, final File dir)
   {
      for (File f : dir.listFiles())
      {
         if (f.isDirectory() && !f.getName().startsWith ("."))
            processDir (out, f);
         else if (f.isFile() && f != outFile && !f.getName().equals ("Errors.tbl"))
            extractVariables (out, f);
      }
   }

   private static void extractVariables (final PrintWriter out, final File file)
   {
      System.out.println ("  > " + file);
      String line = null;
      try
      {
         FileInputStream fis = new FileInputStream (file);
         InputStreamReader isr = new InputStreamReader (fis);
         BufferedReader br = new BufferedReader (isr);
         
         while ((line = br.readLine()) != null)
         {
            if (line.contains ("{"))
            {
               String stripped = line.replace ('{', '[').replace ('}', ']');
               out.println (file + ";" + stripped + ";" + line);
            }
            
            if (line.startsWith(Macros.SUBSET_CHAR))
            {
               Subset subset = new Subset(line);
               String subsetXref = FileUtils.getNameWithoutSuffix(file) + Macros.SUBSET_CHAR + subset.getName();
               out.println (file + "; [" + subsetXref + "] ; {" + subsetXref + "}");
            }
         }
         
         fis.close();
      }
      catch (IOException x)
      {
         System.err.println ("File: " + file);
         System.err.println ("Line: " + line);
         x.printStackTrace (System.err);
      }
   }
   
   public static void main (final String[] args)
   {
      try
      {
         outFile = new File ("data/Tables/Depends.tbl");
         PrintWriter out = new PrintWriter (outFile);
         out.println ("\n? Generated by Depends.java\n");
         out.println (Macros.COLUMN_CHAR + " Table");
         out.println (Macros.COLUMN_CHAR + " Variable");
         out.println (Macros.COLUMN_CHAR + " Value\n");
         
         processDir (out, new File ("data/Tables"));
         
         out.close();
         
         System.out.println ("Variables extraced to: " + outFile);
      }
      catch (IOException x)
      {
         x.printStackTrace (System.err);
      }
   }
}
